name: Azure Function Keep-Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
permissions: {}  # least privileges

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Random Delay and Ping
        run: |
          # Generates random number between 0 and 120 seconds (2 minutes)
          # This effectively shifts the ping time between the 5th and 7th minute
          DELAY=$(( RANDOM % 121 ))
          echo "Waiting for $DELAY seconds to look natural..."
          sleep $DELAY
          
          curl -I -s https://akt-zs.cz/api/keepAlive \
            -o /dev/null -w "Status code: %{http_code}\n"
